---
apiVersion: v1
kind: Service
metadata:
  name: clair-db
spec:
  selector:
    app: clair-db
  ports:
  - port: 5432
    targetPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: clair
spec:
  selector:
    app: clair
  ports:
  - name: first
    protocol: TCP
    port: 6061
    targetPort: 6061
  - name: second
    protocol: TCP
    port: 6060
    targetPort: 6060
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair-db
  labels:
    app: clair-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clair-db
  template:
    metadata:
      labels:
        app: clair-db
    spec:
      containers:
      - name: clair-db
        image: khinkali/postgres:0.0.3
        env:
        - name: POSTGRES_PASSWORD
          value: "password"
        ports:
        - containerPort: 5432
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: clair
  labels:
    app: clair
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clair
  template:
    metadata:
      labels:
        app: clair
    spec:
      containers:
      - name: clair
        image: quay.io/coreos/clair:v2.0.3
        ports:
        - containerPort: 6060
        - containerPort: 6061
        args:
        - -config
        - /config/config.yaml
        volumeMounts:
        - name: config
          mountPath: /config
      volumes:
      - name: config
        configMap:
          name: clair-config
          items:
          - key: config.yaml
            path: config.yaml